import { Theme } from "../Theme";

/**
 * Dracula Dark theme - based on dracula-dark.css
 */
export const DRACULA_DARK_THEME: Theme = {
	id: "dracula-dark",
	name: "Dracula Dark",
	mode: "dark",
	isBuiltin: false,
	colors: {
		"color-blue-1": "#6DCCFF",
		"color-blue-2": "#54B3FF",
		"color-blue-3": "#3B9AE6",
		"color-comment": "#6272A4",
		"color-cyan-1": "#A4FFFF",
		"color-cyan-2": "#8BE9FD",
		"color-cyan-3": "#72D0E4",
		"color-cyan-4": "#5DF5DB",
		"color-green-1": "#69FF94",
		"color-green-2": "#50FA7B",
		"color-green-3": "#37EB62",
		"color-green-4": "#67F858",
		"color-orange-1": "#FFD185",
		"color-orange-2": "#FFB86C",
		"color-orange-3": "#E69F53",
		"color-orange-4": "#F97459",
		"color-pink-1": "#FF92DF",
		"color-pink-2": "#FF79C6",
		"color-pink-3": "#E660AD",
		"color-pink-4": "#F958A8",
		"color-purple-1": "#D6ACFF",
		"color-purple-2": "#BD93F9",
		"color-purple-3": "#A47AE0",
		"color-purple-4": "#7459F8",
		"color-red-1": "#FF6E6E",
		"color-red-2": "#FF5555",
		"color-red-3": "#E63C3C",
		"color-white-4": "#E3E3E8",
		"color-yellow-1": "#FFFFA5",
		"color-yellow-2": "#F1FA8C",
		"color-yellow-3": "#D8E173",
		"color-yellow-4": "#F9F858",
		"Dracula-Background": "#282A36",
		"Dracula-Comment": "#6272A4",
		"Dracula-Current-Line": "#44475A",
		"Dracula-Cyan": "#8BE9FD",
		"Dracula-Dark": "#21222B",
		"Dracula-Foreground": "#F8F8F2",
		"Dracula-Green": "#50FA7B",
		"Dracula-Orange": "#FFB86C",
		"Dracula-Pink": "#FF79C6",
		"Dracula-Purple": "#BD93F9",
		"Dracula-Red": "#FF5555",
		"Dracula-Yellow": "#F1FA8C",
		"tropical-blue": "#62E2F8",
		"tropical-green": "#62F8C3",
		"tropical-lime": "#62F883",
		"tropical-orange": "#F89B62",
		"tropical-pink": "#F48AB7",
		"tropical-purple": "#B07AFF",
		"tropical-red": "#F86862",
		"tropical-tan": "#F8F3C2",
		"tropical-white": "#FFECDB",
		"tropical-yellow": "#F8F37E",
	},
	assignments: {
		"BACKGROUND-PRIMARY": "var(--Dracula-Dark)",
		"BACKGROUND-SECONDARY": "var(--Dracula-Background)",
		"BACKGROUND-HIGHTLIGHT": "var(--Dracula-Comment)",
		"BACKGROUND-CURRENT-LINE": "var(--Dracula-Current-Line)",

		"TEXT": "var(--Dracula-Foreground)",
		"TITLE": "var(--color-cyan-2)",
		"ACCENT": "var(--color-cyan-2)",
		"ACTION": "var(--color-purple-2)",
		"LIST": "var(--color-purple-2)",
		"HEADER": "var(--color-yellow-1)",
		"CARET": "var(--color-cyan-3)",
		"LINK": "var(--tropical-green)",

		"BOLD": "var(--color-cyan-2)",
		"ITALICS": "var(--color-pink-1)",
		"HIGHLIGHT": "var(--color-yellow-1)",
		"STRIKETHROUGH": "var(--tropical-orange)",
		"LINE_BREAK": "var(--color-purple-2)",
		"TAGS": "var(--color-yellow-1)",

		"HEADER-1": "var(--color-pink-1)",
		"HEADER-2": "var(--color-yellow-1)",
		"HEADER-3": "var(--tropical-orange)",
		"HEADER-4": "var(--color-purple-2)",
		"HEADER-5": "var(--color-green-1)",
		"HEADER-6": "var(--color-red-1)",
	},
};
