import { Theme } from "../Theme";

/**
 * Kiro Dark theme - based on kiro-dark.css
 */
export const KIRO_DARK_THEME: Theme = {
	id: "kiro-dark",
	name: "Kiro Dark",
	mode: "dark",
	isBuiltin: false,
	colors: {
		"kiro-blue": "#8dc8fb",
		"kiro-blue-1": "#0c9aa7",
		"kiro-blue-2": "#2d6a9f",
		"kiro-dark": "#211d25",
		"kiro-dark-purple": "#7138cc",
		"kiro-darkest": "#19161d",
		"kiro-gray": "#28242e",
		"kiro-gray-1": "#352f3d",
		"kiro-gray-2": "#938f9b",
		"kiro-green": "#80ffb5",
		"kiro-green-1": "#367c53",
		"kiro-light": "#938f9b",
		"kiro-light-purple": "#e2d3fe",
		"kiro-lightest": "#ffffff99",
		"kiro-orange": "#ffcf99",
		"kiro-orange-1": "#d08025",
		"kiro-pink": "#ff80b5",
		"kiro-pink-1": "#c80e5c",
		"kiro-purple": "#b080ff",
		"kiro-purple-1": "#876eb1",
		"kiro-purple-2": "#8e47ff",
		"kiro-purple-3": "#7138cc",
		"kiro-red": "#ff8080",
		"kiro-red-1": "#993333",
		"kiro-turquoise": "#80f4ff",
		"kiro-white": "#ffffff",
		"kiro-white-1": "#eae8ed",
		"kiro-white-2": "#f2f1f4",
		"kiro-white-3": "#dcdadf",
	},
	assignments: {
		"BACKGROUND-PRIMARY": "var(--kiro-dark)",
		"BACKGROUND-SECONDARY": "var(--kiro-darkest)",
		"BACKGROUND-HIGHTLIGHT": "var(--kiro-gray-1)",
		"BACKGROUND-CURRENT-LINE": "var(--kiro-gray)",

		"TEXT": "var(--kiro-white)",
		"TITLE": "var(--kiro-green)",
		"ACCENT": "var(--kiro-turquoise)",
		"ACTION": "var(--kiro-pink)",
		"LIST": "var(--kiro-blue)",
		"HEADER": "var(--kiro-red)",
		"CARET": "var(--kiro-turquoise)",
		"LINK": "var(--kiro-turquoise)",

		"BOLD": "var(--kiro-green)",
		"ITALICS": "var(--kiro-pink)",
		"HIGHLIGHT": "var(--kiro-orange)",
		"STRIKETHROUGH": "var(--kiro-blue)",
		"LINE_BREAK": "var(--kiro-purple)",
		"TAGS": "var(--kiro-orange)",

		"HEADER-1": "var(--kiro-purple)",
		"HEADER-2": "var(--kiro-orange)",
		"HEADER-3": "var(--kiro-blue)",
		"HEADER-4": "var(--kiro-red)",
		"HEADER-5": "var(--kiro-green)",
		"HEADER-6": "var(--kiro-purple)",
	},
};
