import { Theme } from "../Theme";

/**
 * Tropical Dark theme - based on tropical-dark.css
 */
export const TROPICAL_DARK_THEME: Theme = {
	id: "tropical-dark",
	name: "Tropical Dark",
	mode: "dark",
	isBuiltin: false,
	colors: {
        "tropical-blue": "#62E2F8",
        "tropical-orange": "#F89B62",
        "tropical-red": "#F86862",
        "tropical-green": "#62F8C3",
        "tropical-yellow": "#F8F37E",
        "tropical-purple": "#B07AFF",
        "tropical-pink": "#F48AB7",
        "tropical-lime": "#62F883",
        "tropical-tan": "#F8F3C2",
        "tropical-white": "#FFECDB",
        "tropical-blue-faded": "rgba(98,226,248,0.8)",
        "tropical-orange-faded": "rgba(248,155,98,1.0)",
        "tropical-red-faded": "rgba(248,104,98,0.8)",
        "tropical-green-faded": "rgba(98,248,195,0.5)",
        "tropical-yellow-faded": "rgba(248,243,126,0.5)",
        "tropical-purple-faded": "rgba(176,122,255,0.6)",
        "tropical-pink-faded": "rgba(244,138,183,1.0)",
        "tropical-lime-faded": "rgba(98,248,131,0.5)",
        "alt-lime": "#B4FFD6",
        "alt-blue": "#1C468B",
        "apple-blue": "#007AFF",
        "dark-gray": "rgb(50,50,50)",
        "kiro-dark": "#211d25",
		"kiro-darkest": "#19161d",
		"kiro-gray": "#28242e",
		"kiro-gray-1": "#352f3d",
        "kiro-white": "#ffffff",
	},
	assignments: {
		"BACKGROUND-PRIMARY": "var(--kiro-dark)",
		"BACKGROUND-SECONDARY": "var(--kiro-darkest)",
		"BACKGROUND-HIGHTLIGHT": "var(--kiro-gray-1)",
		"BACKGROUND-CURRENT-LINE": "var(--kiro-gray)",

		"TEXT": "var(--kiro-white)",
		"TITLE": "var(--tropical-blue)",
		"ACCENT": "var(--tropical-pink)",
		"ACTION": "var(--tropical-red)",
		"LIST": "var(--tropical-orange)",
		"HEADER": "var(--tropical-yellow)",
		"CARET": "var(--tropical-blue)",
		"LINK": "var(--tropical-green)",

		"BOLD": "var(--tropical-pink)",
		"ITALICS": "var(--tropical-purple)",
		"HIGHLIGHT": "var(--tropical-orange)",
		"STRIKETHROUGH": "var(--tropical-red)",
		"LINE_BREAK": "var(--tropical-orange)",
		"TAGS": "var(--tropical-yellow)",

		"HEADER-1": "var(--tropical-pink)",
		"HEADER-2": "var(--tropical-purple)",
		"HEADER-3": "var(--tropical-orange)",
		"HEADER-4": "var(--tropical-red)",
		"HEADER-5": "var(--tropical-green)",
		"HEADER-6": "var(--tropical-yellow)",
	},
};
